# build with one of the following commands:

#  podman build <dir_where_this_file_is>
#
#  docker build <dir_where_this_file_is> -t manylinux
FROM quay.io/pypa/manylinux_2_28_x86_64
RUN yum install -y gmp-c++ gmp-devel clang-devel-17.0.6 llvm-devel-17.0.6

